### ISSUE TITLE
Web UI Testing E2E full test suite for e-commerce

### ISSUE THREAD

**Issue by Lucas-Runner** [Lucas-Runner/e-commerce-webtesting#1]
## Task Description

Package of web automation tests based on JavaScript and Playwright frameworks for end-to-end user interface and main functions testing of an e-commerce website application

## Details

The test package is designed around the main user functionalities:

- User registration procedure
- User Log-in procedure
- Product cart validity
- Purchase confirmation

## Acceptance Criteria

- [x] Ensure user registration tools work and "user page" contains expected data
- [x] Log-in with user data generated during "registration procedure"
- [x] Products added to cart are correct and match selected products "products page"
- [x] Purchase procedure results in purchase confirmation matching selected product
